### ISSUE TITLE
PSA 1.4.4

### ISSUE THREAD

**Issue by hokutonanto** [PhysicalAddons/physical-starlight-and-atmosphere#66] opened 2022-02-27 02:50 UTC
**Describe the bug**
The latest beta seems to crash with scenes containing a decent amount of geometry.

**General information**
- Blender version: 3.0.1
- Addon version: 1.4.4 beta
- Engine: Cycles
- Operating System: Windows 10
- Other info that could be useful:  Threadripper 1950x, (2) 1080ti

**To Reproduce**
PSA looks fine in the viewport, but causes Blender to crash when I hit render.

Crash log attached.

This is the scene I was trying to render.
In the image below, I had to turn off PSA, and use an HDRI image instead
![image](https://user-images.githubusercontent.com/23059969/155866103-05a1e55c-8fd7-42d6-bf48-ec86ee36ce7e.png)

[moss -02.crash.txt](https://github.com/PhysicalAddons/physical-starlight-and-atmosphere/files/8147883/moss.-02.crash.txt)

**Comment by karlisup** [comment] 2022-03-03 23:18
Hi @hokutonanto,
Thank you for the report and I am sorry that instead of using PSA you had to use HDRI! We have fixed this issue with the upcoming PSA version 1.5.0. Could you report if the issue persists on 1.5.0? Till then, I'll close this issue as a duplicate of #43

**Closed as completed by karlisup** 2022-03-03 23:18 UTC
Labels: bug

**Comment by hokutonanto** [comment] 2022-03-04 05:25
Thank you, @karlisup 

Np, just a test I was doing, nothing serious :)
I can confirm that 1.5 works great! Really glad you guys figured this out. And the new system, it's a pleasure to use!

PSA version
![image](https://user-images.githubusercontent.com/23059969/156704700-3b7814f0-2c56-4532-b1fb-2b545c245efb.png)
