### ISSUE TITLE
Instant crash when trying to render image

### ISSUE THREAD

**Issue by kinchd** [PhysicalAddons/physical-starlight-and-atmosphere#62] opened 2022-02-05 03:47 UTC
**Describe the bug**
Blender instant crashes every time when trying to render image using the latest plugin

**General information**
- Blender version: 3.0.0, 3.0.1
- Addon version: 1.4.4
- Engine: Evee
- Operating System: macOS Monterey 12.1
- Other info that could be useful: MacBook Pro (2022) 

**To Reproduce**
-Open Blender 3.0
-turn on Physical Starlight plugin
-render the base setup
-crash occurs on every attempt

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
![Screen Shot 2022-02-04 at 7 45 30 PM](https://user-images.githubusercontent.com/99061421/152627612-923e7ce0-eabe-4103-b8e4-bb6f0a9b9ed2.png)
![Screen Shot 2022-02-04 at 7 45 51 PM](https://user-images.githubusercontent.com/99061421/152627616-c9a8f8a9-1203-4c0c-9644-9df25da9f4c3.png)

**Comment by victorktliu** [comment] 2022-02-05 10:19
Same thing here on a Asus G14 Running AMD Ryzen 9

**Comment by karlisup** [comment] 2022-02-05 10:27
Hi @victorktliu,
Could you try locking interface [like so](https://github.com/PhysicalAddons/physical-starlight-and-atmosphere/issues/43#issuecomment-946002816), before doing the render?
![image](https://user-images.githubusercontent.com/3999661/152638316-5f593273-7fe0-4fb4-9c24-817e13326d8e.png)

As an alternative try [this approach](https://github.com/PhysicalAddons/physical-starlight-and-atmosphere/issues/43#issuecomment-1015360519).

These are just workarounds that will/should be fixed with the upcoming release.
Duplicate of #43

**Closed as completed by karlisup** 2022-02-05 10:27 UTC
Labels: bug
