### ISSUE TITLE
Direct lighting disappearing when rendering final image and adjusting the Azimuth/Elevation settings

### ISSUE THREAD

**Issue by M0D1FY** [PhysicalAddons/physical-starlight-and-atmosphere#24] opened 2020-08-04 01:45 UTC
I'm having multiple issues:

1: The Direct lighting in my scene disappears when adjusting the Azimuth and Elevation settings in Cycles. Hitting the reset buttons doesn't help. 

2: Also hitting the reset button under the Atmosphere menu causes my scene to go completely dark, almost pitch black. 

3: Hitting the Render Image causes the direct lighting to disappear from the final image as well.

It seems to only be happening with a particular scene of mine. If I create a new blank scene everything seems to be working fine. 

As it stands I'm unable render my final image.

I've attached a video in the zip file illustrating the issues. Apologies for the poor video quality but there's a 10mb limit for uploads.

Info:
Blender 2.83.3 with Starlight/Atomsphere 1.2.2
Windows 10
Ryzen Threadripper 1950x
GTX 1080Ti

[(Output002)2020-08-03 18-01-34-2.zip](https://github.com/PhysicalAddons/physical-starlight-and-atmosphere/files/5019571/Output002.2020-08-03.18-01-34-2.zip)

**Comment by karlisup** [comment] 2020-08-10 11:51
Hi @M0D1FY,
> Apologies for the poor video quality but there's a 10mb limit for uploads.

Thank you for the video and your patience! Could you please reproduce it once more and send me a screenshot of the settings you are using? I tried to reproduce the issue, but I didn't manage to do it without knowing the addon parameters.

> 1: The Direct lighting in my scene disappears

What do you mean by that? I am asking it because what I see in the video feels like a way it should be, but maybe I am wrong and I don't see something you do. 

> Hitting the reset buttons doesn't help.

For the Sun position, the reset button does reset every single Sun property **except** `Azimuth` and `Elevation`. 

> 3: Hitting the Render Image causes the direct lighting to disappear from the final image as well.

Does it go completely dark? If so this sounds like a bug from the previous addon version. My hypothesis is that [reinstalling addon](https://starlight-manual.readthedocs.io/en/latest/installation/#installation-troubleshooting) could solve this issue.

**Comment by M0D1FY** [comment] 2020-08-11 22:11
Hi @karlisup 

What I meant by the Direct lighting disappearing is that if I changed the Azimuth or Elevation by as little as one degree the Direct lighting completely disappears and is only lit by ambient light or the Atmosphere. As soon as I hit reset on the Atmosphere menu, that's when the scene goes dark because I'm assuming that's what is lighting the scene given the direct lighting is no longer working.

In the beginning of the video when I change the Azimuth, it starts at 170 and you can see the golden sunlight hitting the buildings, I then change it to 140 after which the direct lighting disappears. I change it back to 170 or any number and there is no longer any golden direct sunlight hitting the buildings or anything direct lighting change. It's more obvious if you look at the ground shadows and the golden light cast on the ground and building screen right. 

I did try uninstalling and reinstalling from scratch multiple times before posting the issue, but that didn't help. At least initially it didn't help.

I did run into something peculiar- at one point I changed the name of the default Scene Collection>'Collection' to 'Scene' which is where the Sun light created by the addon lived. I was getting desperate so thought maybe there was a naming dependency of some sort so I changed the name back to Collection and it seems to have fixed the problem. 

What's odd though is now I can't reproduce the issue, in any of my scenes, including the scene where I changed the Collection name. I'm not exactly sure what fixed it. It was either the changing of the Collection name where the Sun object lives which doesn't really make sense or a combination of the clean install and changing the name of the Collection.

Either way, everything seems to be working normally again. 

Here are the settings I had at the time of the problems which I backed up in case I needed to recreate the scene from scratch.

![2020-08-03 17_30_43-Window](https://user-images.githubusercontent.com/69177400/89952518-3ebeb980-dbe2-11ea-9e2d-54c7c6d3aa41.png)

**Comment by karlisup** [comment] 2020-08-13 09:34
Hi,
Thank you for such a detailed description of the disappearing direct light issue and settings you used!  It is very helpful for reproducing the issue. 
> I did run into something peculiar- at one point I changed the name of the default Scene Collection>'Collection' to 'Scene' which is where the Sun light created by the addon lived. I was getting desperate so thought maybe there was a naming dependency of some sort so I changed the name back to Collection and it seems to have fixed the problem.

This is very odd. I scanned through the code and couldn't find a dependency linked to the naming. Also changed my Collection name and played with it a bit, but couldn't reproduce the issue. 

> Either way, everything seems to be working normally again.

For now, I'll close the issue and just keep in mind in case another similar issue pops up. Then I will know where to look and maybe the information you provided complements the other issue description and we can fix the issue if it ever appears again.

**Closed by karlisup** 2020-08-13 09:34 UTC
