### ISSUE TITLE
`use real world physical values` feature doesn't work!

### ISSUE THREAD

**Issue by Githubartist1111111111111111111** [PhysicalAddons/physical-starlight-and-atmosphere#85] opened 2023-04-03 18:37 UTC
Hi team i have just bought this add on and it is ot working when i click on physical environment box check in nothing happens .Please solve this query as i have apid for this plugin  .

**Comment by karlisup** [comment] 2023-04-04 09:19
Hey @Githubartist1111111111111111111,
Thank you for your feedback! Indeed this is an issue and we have internally fixed it and waiting to release it with a bunch of almost finished other enhancements. It seems that a better way would be releasing this as a hot fix and release other enhancements in a separate release.

Will ping you whenever the hot fix is released.

**Comment by Githubartist1111111111111111111** [comment] 2023-04-04 09:40
So when will it be released? Till then what should I do?

**Comment by karlisup** [comment] 2023-04-04 10:40
Will jump the task queue and release it today. Sorry for any inconvenience caused by this issue.
The release process takes quite a while (automated testing, manual testing, packaging, and releasing to various e-stores) which is the reason I cannot provide you with a new version right now. Thank you for your patience.

**Comment by karlisup** [comment] 2023-04-04 12:58
@Githubartist1111111111111111111 I am pleased to inform you that the bugfix has been successfully released. You should be able to obtain it from the store where you made the purchase. As a result, I will be closing this ticket as the issue has been addressed. Should you encounter any further problems, please do not hesitate to reopen the ticket and bring it to our attention.

**Closed as completed by karlisup** 2023-04-04 12:58 UTC
Labels: bug

**Comment by Githubartist1111111111111111111** [comment] 2023-04-04 16:34
Can you share me the link where will I get ??
