### ISSUE TITLE
name 'RIG_PT_ObjectFogWT' is not defined

### ISSUE THREAD

**Issue by VerdeStudios** [PhysicalAddons/physical-starlight-and-atmosphere#51] opened 2021-08-28 21:22 UTC
**Describe the bug**
After the addon's zip file is downloaded and installed, blender won't allow it to be enabled.
Blender gives this error:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 386, in enable
    mod.register()
  File "C:\Users\verde\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\physical-starlight-atmosphere\__init__.py", line 197, in register
    classes = get_classes()
  File "C:\Users\verde\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\physical-starlight-atmosphere\__init__.py", line 176, in get_classes
    RIG_PT_ObjectFogWT,
NameError: name 'RIG_PT_ObjectFogWT' is not defined

**General information**
- Blender version: 2.93.1
- Addon version: 1.4.2 Beta
- Engine: Cycles
- Operating System: Windows 10, 
- Other info that could be useful:  GPU GTX 1650, 16 GB DDR4 RAM

**To Reproduce**
1. Download the most recent addon version.
2. Install it in blender preferences.
3.Check the enable box.

**Comment by karlisup** [comment] 2021-09-07 13:36
Hi @VerdeStudios,
Thank you for your patience! Try removing the previous version before installing a new one. Here's a link to PSA addon documentation - [updating troubleshooting](https://www.physicaladdons.com/psa/updating/#troubleshooting) page.

**Comment by karlisup** [comment] 2021-09-08 15:11
Duplicate of #31

**Closed as completed by karlisup** 2021-09-08 15:11 UTC
Labels: bug
