### ISSUE TITLE
Phys. Atmos and Star

### ISSUE THREAD

**Issue by Ingapambi** [PhysicalAddons/physical-starlight-and-atmosphere#33] opened 2021-01-04 05:23 UTC
**Describe the bug**
[Installed 1.3 but won't enable.]

**General information**
- Blender version: [e.g. 2.92]
- Addon version: [e.g. 1.3]
- Engine: [Cycles]
- Operating System: [MacOS(Big Sur), etc.]
- Other info that could be useful: [e.g. CPU, GPU, etc.]: 

**To Reproduce**
[Use preferences>addons>install. Then try to enable
<img width="1298" alt="Screen Shot 2021-01-03 at 9 16 26 PM" src="https://user-images.githubusercontent.com/44510383/103503677-daf39200-4e09-11eb-82c4-f4ac7cd291b3.png">
]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Comment by karlisup** [comment] 2021-01-04 14:53
Hi @Ingapambi ,
This should be a duplicate of #31. Take look if this fixes it for you and let me know.

**Comment by karlisup** [comment] 2021-02-01 14:10
I'll close this issue as it's currently inactive and potentially fixed. If the issue persists, feel free to reopen this ticket.

**Closed as completed by karlisup** 2021-02-01 14:10 UTC
Labels: bug
