### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by pdesopo** [PhysicalAddons/physical-starlight-and-atmosphere#19] opened 2020-06-27 22:12 UTC
I have installed the latest version 1.2.1, and I'm getting this error

`Traceback (most recent call last):
  File "C:\...\E_cycles_2.90_v20200622_win\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'physical-starlight-atmosphere-1'`

**Comment by karlisup** [comment] 2020-06-28 09:07
Duplicate of #18

**Closed by karlisup** 2020-06-28 09:07 UTC
