### ISSUE TITLE
Sun disc blows out Eevee scene

### ISSUE THREAD

**Issue by gabrielmontagne** [PhysicalAddons/physical-starlight-and-atmosphere#12] opened 2020-06-11 07:04 UTC
**Describe the bug**

Sky looks great, but if I turn on the sun disk, the scene blows out in Eevee -- see attached screenshots.

**General information**
- Blender version: 2.83.0, "Physical Starliight" addon version 1.2
- Engine: Eevee
- Operating System: Linux
- Other info that could be useful: Running on CPU

**To Reproduce**

1. Create a new scene
2. Turn on "Physical Atmosphere"
3. Make sure you're in Eevee
4. Turn "viewport shading" to Rendered.

**Screenshots**

Cycles with sun disc on, 

![2020-06-11-075825_1250x558_scrot](https://user-images.githubusercontent.com/95913/84355030-d3dd0c00-abb9-11ea-802e-222836174f84.png)

Eevee with sun disc on, 

![2020-06-11-075839_1284x572_scrot](https://user-images.githubusercontent.com/95913/84355032-d50e3900-abb9-11ea-8d38-b956b3441fb4.png)

Eeve with sun disc off, 

![2020-06-11-075854_1287x581_scrot](https://user-images.githubusercontent.com/95913/84355035-d5a6cf80-abb9-11ea-9e4c-0f30ebc8878e.png)

**Comment by karlisup** [comment] 2020-08-13 13:01
Hi @gabrielmontagne,
Thank you for your patience! I did reproduce this on my laptop which has `Intel Iris Plus Graphics 650 1536 MB` graphics card and this bug has been reported before and is duplicate of #3. Thank you for reporting `Sun Disc` workaround. I'll add it to the workaround list. Please, follow #3 issue for further updates.

**Closed** 2020-08-13 13:02 UTC
Labels: bug
