### ISSUE TITLE
beta 1.4.3 problem

### ISSUE THREAD

**Issue by charliemagee** [PhysicalAddons/physical-starlight-and-atmosphere#56] opened 2021-12-08 18:17 UTC
Installed beta 1.4.3 to use clouds. Had problems with scene not updating on some changes, not all.

Removed addon from Prefs list. Tried to install 1.3.2, received error seen in attached screenshot. Now I can't use either version. Please help.
![Screen Shot 2021-12-08 at 10 13 13 AM](https://user-images.githubusercontent.com/897319/145261909-7137baa2-a405-4855-81cd-caf450de8f29.png)

**Comment by charliemagee** [comment] 2021-12-08 18:30
I quit and restarted Blender and was able to turn 1.4 back on. I turned off the experimental features and it seems to be working properly.

I'm on a MacBook Pro, in case that matters.

**Comment by karlisup** [comment] 2021-12-08 23:01
Hi Charlie,
To avoid we [suggest ](https://github.com/PhysicalAddons/physical-starlight-and-atmosphere/issues/31#issuecomment-744243641)completely removing the previous version before installing the new one.
Sorry for any inconvenience caused.
Closed as duplicate of #31

**Closed as completed by karlisup** 2021-12-08 23:01 UTC
