### ISSUE TITLE
Problems updating to v1.3 ('RIG_PT_BinarySunWT' is not defined)

### ISSUE THREAD

**Issue by Adibese** [PhysicalAddons/physical-starlight-and-atmosphere#31] opened 2020-12-14 07:35 UTC
**Describe the bug**
[Replace this with a clear and concise description of what the issue is about.]

**General information**
- Blender version: 2.9.1
- Addon version: 1.3.0
- Engine: Evee
- Operating System: Windows 10

Install over old version on Blender 2.9.1. After install, check the Enable button. Right away an error message comes up.

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\zonda\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\physical-starlight-atmosphere\__init__.py", line 83, in <module>
    RIG_PT_BinarySunWT,
NameError: name 'RIG_PT_BinarySunWT' is not defined

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Comment by karlisup** [comment] 2020-12-14 07:44
Hi @Adibese,
Try deleting the old version before uploading a new one as described in [updating](https://www.physicaladdons.com/psa/updating/) section. Seems like a duplicate of #28 and #30.

**Comment by Adibese** [comment] 2020-12-14 08:06
Thank you, I was sure I had it deleted, but I went back to previous scripts and deleted the older versions and it works now.

**Comment by karlisup** [comment] 2021-02-05 13:11
I'll reopen this issue as it causes a bad user experience. Users should not have to uninstall the previous version before installing the new one.

**Comment by karlisup** [comment] 2021-07-01 13:45
Lately have no reports regarding this issue.

**Closed as completed by karlisup** 2021-07-01 13:45 UTC
Labels: bug
